
# 04 NumPy and Basic Pandas

# NumPy

In [3]:
import numpy as np

## Basic NumPy Arrays

In [5]:
price_list = [269.36, 365.83, 13.68, 44.02, 13.5, 42.62,569.356]
price_array = np.array(price_list)
print(price_array, type(price_array))

[269.36  365.83   13.68   44.02   13.5    42.62  569.356] <class 'numpy.ndarray'>


In [9]:
Ar = np.array([[1,3,6],[2,4,5],[2,6,8]])
print(Ar, type(Ar))

[[1 3 6]
 [2 4 5]
 [2 6 8]] <class 'numpy.ndarray'>


In [10]:
print(Ar.shape)

(3, 3)


In [12]:
print(Ar[0])
print(Ar[1])
print(Ar[2])

[1 3 6]
[2 4 5]
[2 6 8]


In [15]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])
print('the thrid column: ',Ar[:,2])

the first column:  [1 2 2]
the second column:  [3 4 6]
the thrid column:  [6 5 8]


## Array Functions

In [16]:
print(np.log(price_array))

[5.59604877 5.90216874 2.61593491 3.78464408 2.60268969 3.75232363
 6.3445059 ]


In [18]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

188.338
202.26497992485008
1318.366
569.356


# Pandas

In [19]:
import pandas as pd

## Series

In [27]:
price = [13.73, 45.83, 143.68, 144.02, 143.5, 142.62,68.65]
s = pd.Series(price)
s

0     13.73
1     45.83
2    143.68
3    144.02
4    143.50
5    142.62
6     68.65
dtype: float64

In [33]:
s = pd.Series(price,index = [1,2,3,4,5,6,7])
s

1     13.73
2     45.83
3    143.68
4    144.02
5    143.50
6    142.62
7     68.65
dtype: float64

In [34]:
s.index = [7,6,5,4,3,2,1]
s

7     13.73
6     45.83
5    143.68
4    144.02
3    143.50
2    142.62
1     68.65
dtype: float64

In [36]:
print(s[2:])
print(s[:-3])

5    143.68
4    144.02
3    143.50
2    142.62
1     68.65
dtype: float64
7     13.73
6     45.83
5    143.68
4    144.02
dtype: float64


In [37]:
print(s[5])
s[5] = 0
print(s)

143.68
7     13.73
6     45.83
5      0.00
4    144.02
3    143.50
2    142.62
1     68.65
dtype: float64


In [38]:
s = pd.Series(price, name = 'Price suggested List')
print(s)
print(s.name)

0     13.73
1     45.83
2    143.68
3    144.02
4    143.50
5    142.62
6     68.65
Name: Price suggested List, dtype: float64
Price suggested List


In [53]:
print(s.describe())

count      7.00000
mean     100.29000
std       56.14498
min       13.73000
25%       57.24000
50%      142.62000
75%      143.59000
max      144.02000
Name: Price suggested List, dtype: float64


## Time Index

In [54]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06', '2017-01-07'],
              dtype='datetime64[ns]', freq='D')
2017-01-01     13.73
2017-01-02     45.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
2017-01-07     68.65
Freq: D, Name: Price suggested List, dtype: float64


In [60]:
s.index = [7,6,5,4,3,2,1]
print(s)
print(s[1])

7     13.73
6     45.83
5    143.68
4    144.02
3    143.50
2    142.62
1     68.65
Name: Price suggested List, dtype: float64
68.65


In [57]:
print(s.iloc[6])

68.65


In [62]:
s.index = time_index
print(s['2017-01-03'])

143.68


In [65]:
print(s['2017-01-02':'2021-10-18'])

2017-01-02     45.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
2017-01-07     68.65
Freq: D, Name: Price suggested List, dtype: float64


In [66]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    13.73
2017-01-02    45.83
2017-01-07    68.65
Name: Price suggested List, dtype: float64
[2017-01-01    False
2017-01-02    False
2017-01-03     True
2017-01-04     True
2017-01-05     True
2017-01-06     True
2017-01-07    False
Freq: D, Name: Price suggested List, dtype: bool]
