# PLU SymPy

In [39]:
from sympy import Matrix,init_printing, eye, zeros
init_printing()

In [46]:
import sympy 
import numpy as np
def PLU(A,k):
    U = A.copy()
    shape_a = U.shape
    n = shape_a[0]
    L = np.eye(n)
    P = np.eye(n)
    for i in range(n):
        k = i
        comp = abs(U[i, i])
        for j in range(i, n):
            if abs(U[j, i]) > comp:
                k = j
                comp = abs(U[j, i])
        line_u = U[k, :].copy()
        U[k, :] = U[i, :]
        U[i, :] = line_u
        line_p = P[k, :].copy()
        P[k, :] = P[i, :]
        P[i, :] = line_p
        for j in range(i + 1, n):
            g = U[j, i] / U[i, i]
            L[j, i] = g
            U[j, :] -= g * U[i, :]
    return L, U, P


In [40]:
A = Matrix([[-2,2,-1], [6,-6,7], [3,-8,4]])
A

⎡-2  2   -1⎤
⎢          ⎥
⎢6   -6  7 ⎥
⎢          ⎥
⎣3   -8  4 ⎦

In [41]:
P,L,U = PLU(A,0)

In [7]:
P

array([[ 1.        ,  0.        ,  0.        ],
       [-0.33333333,  1.        ,  0.        ],
       [ 0.5       ,  0.        ,  1.        ]])

In [8]:
L

⎡6  -6   7 ⎤
⎢          ⎥
⎢0  -5  1/2⎥
⎢          ⎥
⎣0  0   4/3⎦

In [9]:
U

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [10]:
P,L,U = PLU(A,1)

Matrix([[-2, 2, -1], [6, -6, 7], [3, -8, 4]])
Matrix([[6, -6, 7], [-2, 2, -1], [3, -8, 4]])
Matrix([[6, -6, 7], [0, 0, 4/3], [0, -5, 1/2]])
Matrix([[6, -6, 7], [0, -5, 1/2], [0, 0, 4/3]])
Matrix([[6, -6, 7], [0, -5, 1/2], [0, 0, 4/3]])
Matrix([[6, -6, 7], [0, -5, 1/2], [0, 0, 4/3]])


In [11]:
P

array([[ 1.        ,  0.        ,  0.        ],
       [-0.33333333,  1.        ,  0.        ],
       [ 0.5       ,  0.        ,  1.        ]])

In [12]:
L

⎡6  -6   7 ⎤
⎢          ⎥
⎢0  -5  1/2⎥
⎢          ⎥
⎣0  0   4/3⎦

In [13]:
U

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [14]:
P,L,U = PLU(A,2)

Matrix([[-2, 2, -1], [6, -6, 7], [3, -8, 4]])
Matrix([[6, -6, 7], [-2, 2, -1], [3, -8, 4]])
Matrix([[6, -6, 7], [0, 0, 4/3], [0, -5, 1/2]])
Matrix([[6, -6, 7], [0, -5, 1/2], [0, 0, 4/3]])
Matrix([[6, -6, 7], [0, -5, 1/2], [0, 0, 4/3]])
Matrix([[6, -6, 7], [0, -5, 1/2], [0, 0, 4/3]])


In [15]:
P

array([[ 1.        ,  0.        ,  0.        ],
       [-0.33333333,  1.        ,  0.        ],
       [ 0.5       ,  0.        ,  1.        ]])

In [16]:
L

⎡6  -6   7 ⎤
⎢          ⎥
⎢0  -5  1/2⎥
⎢          ⎥
⎣0  0   4/3⎦

In [17]:
U

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [47]:
from sympy import  N
N(U)

AttributeError: ignored

In [43]:
# Now, generate a full rank matrix and test the naive implementation

import sympy 
import numpy as np

N = 6
A = sympy.zeros(N)
for i in range(N):
    for j in range(N):
        A[i, j] = 2 + sympy.Rational(1,i*j+1)

A

⎡3   3     3     3     3     3  ⎤
⎢                               ⎥
⎢3  5/2   7/3   9/4   11/5  13/6⎥
⎢                               ⎥
⎢                            23 ⎥
⎢3  7/3   11/5  15/7  19/9   ── ⎥
⎢                            11 ⎥
⎢                               ⎥
⎢                21    27    33 ⎥
⎢3  9/4   15/7   ──    ──    ── ⎥
⎢                10    13    16 ⎥
⎢                               ⎥
⎢                27    35    43 ⎥
⎢3  11/5  19/9   ──    ──    ── ⎥
⎢                13    17    21 ⎥
⎢                               ⎥
⎢          23    33    43    53 ⎥
⎢3  13/6   ──    ──    ──    ── ⎥
⎣          11    16    21    26 ⎦

In [20]:
np.array(A).astype(np.float64)

array([[3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        ],
       [3.        , 2.5       , 2.33333333, 2.25      , 2.2       ,
        2.16666667],
       [3.        , 2.33333333, 2.2       , 2.14285714, 2.11111111,
        2.09090909],
       [3.        , 2.25      , 2.14285714, 2.1       , 2.07692308,
        2.0625    ],
       [3.        , 2.2       , 2.11111111, 2.07692308, 2.05882353,
        2.04761905],
       [3.        , 2.16666667, 2.09090909, 2.0625    , 2.04761905,
        2.03846154]])

In [21]:
np.linalg.matrix_rank(np.array(A).astype(np.float64))

6

In [22]:
A[1, 1] = 3

In [23]:
A

⎡3   3     3     3     3     3  ⎤
⎢                               ⎥
⎢3   3    7/3   9/4   11/5  13/6⎥
⎢                               ⎥
⎢                            23 ⎥
⎢3  7/3   11/5  15/7  19/9   ── ⎥
⎢                            11 ⎥
⎢                               ⎥
⎢                21    27    33 ⎥
⎢3  9/4   15/7   ──    ──    ── ⎥
⎢                10    13    16 ⎥
⎢                               ⎥
⎢                27    35    43 ⎥
⎢3  11/5  19/9   ──    ──    ── ⎥
⎢                13    17    21 ⎥
⎢                               ⎥
⎢          23    33    43    53 ⎥
⎢3  13/6   ──    ──    ──    ── ⎥
⎣          11    16    21    26 ⎦

In [24]:
np.linalg.matrix_rank(np.array(A).astype(np.float64))

6

In [25]:
P,L,U = PLU(A,0)

Matrix([[3, 3, 3, 3, 3, 3], [3, 3, 7/3, 9/4, 11/5, 13/6], [3, 7/3, 11/5, 15/7, 19/9, 23/11], [3, 9/4, 15/7, 21/10, 27/13, 33/16], [3, 11/5, 19/9, 27/13, 35/17, 43/21], [3, 13/6, 23/11, 33/16, 43/21, 53/26]])
Matrix([[3, 3, 3, 3, 3, 3], [3, 3, 7/3, 9/4, 11/5, 13/6], [3, 7/3, 11/5, 15/7, 19/9, 23/11], [3, 9/4, 15/7, 21/10, 27/13, 33/16], [3, 11/5, 19/9, 27/13, 35/17, 43/21], [3, 13/6, 23/11, 33/16, 43/21, 53/26]])
Matrix([[3, 3, 3, 3, 3, 3], [0, 0, -2/3, -3/4, -4/5, -5/6], [0, -2/3, -4/5, -6/7, -8/9, -10/11], [0, -3/4, -6/7, -9/10, -12/13, -15/16], [0, -4/5, -8/9, -12/13, -16/17, -20/21], [0, -5/6, -10/11, -15/16, -20/21, -25/26]])
Matrix([[3, 3, 3, 3, 3, 3], [0, -5/6, -10/11, -15/16, -20/21, -25/26], [0, -2/3, -4/5, -6/7, -8/9, -10/11], [0, -3/4, -6/7, -9/10, -12/13, -15/16], [0, -4/5, -8/9, -12/13, -16/17, -20/21], [0, 0, -2/3, -3/4, -4/5, -5/6]])
Matrix([[3, 3, 3, 3, 3, 3], [0, -5/6, -10/11, -15/16, -20/21, -25/26], [0, 0, -4/55, -3/28, -8/63, -20/143], [0, 0, -3/77, -9/160, -6/91, -1

In [26]:
P

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.8       , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.9       , 0.05844156, 1.        , 0.        ,
        0.        ],
       [1.        , 0.96      , 0.02424242, 0.19329389, 1.        ,
        0.        ],
       [1.        , 0.        , 0.10909091, 0.49038462, 0.61136249,
        1.        ]])

In [27]:
L

⎡3   3     3     3      3        3    ⎤
⎢                                     ⎥
⎢         -10   -15    -20      -25   ⎥
⎢0  -5/6  ────  ────   ────     ────  ⎥
⎢          11    16     21       26   ⎥
⎢                                     ⎥
⎢0   0    -2/3  -3/4   -4/5     -5/6  ⎥
⎢                                     ⎥
⎢               -39   -688            ⎥
⎢0   0     0    ────  ─────    -7/143 ⎥
⎢               1540  17325           ⎥
⎢                                     ⎥
⎢                               123   ⎥
⎢0   0     0     0    2/6825   ────── ⎥
⎢                              208208 ⎥
⎢                                     ⎥
⎢                               -32   ⎥
⎢0   0     0     0      0     ────────⎥
⎣                             25882857⎦

In [28]:
U

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [29]:
P,L,U = PLU(A,1)

Matrix([[3, 3, 3, 3, 3, 3], [3, 3, 7/3, 9/4, 11/5, 13/6], [3, 7/3, 11/5, 15/7, 19/9, 23/11], [3, 9/4, 15/7, 21/10, 27/13, 33/16], [3, 11/5, 19/9, 27/13, 35/17, 43/21], [3, 13/6, 23/11, 33/16, 43/21, 53/26]])
Matrix([[3, 3, 3, 3, 3, 3], [3, 3, 7/3, 9/4, 11/5, 13/6], [3, 7/3, 11/5, 15/7, 19/9, 23/11], [3, 9/4, 15/7, 21/10, 27/13, 33/16], [3, 11/5, 19/9, 27/13, 35/17, 43/21], [3, 13/6, 23/11, 33/16, 43/21, 53/26]])
Matrix([[3, 3, 3, 3, 3, 3], [0, 0, -2/3, -3/4, -4/5, -5/6], [0, -2/3, -4/5, -6/7, -8/9, -10/11], [0, -3/4, -6/7, -9/10, -12/13, -15/16], [0, -4/5, -8/9, -12/13, -16/17, -20/21], [0, -5/6, -10/11, -15/16, -20/21, -25/26]])
Matrix([[3, 3, 3, 3, 3, 3], [0, -5/6, -10/11, -15/16, -20/21, -25/26], [0, -2/3, -4/5, -6/7, -8/9, -10/11], [0, -3/4, -6/7, -9/10, -12/13, -15/16], [0, -4/5, -8/9, -12/13, -16/17, -20/21], [0, 0, -2/3, -3/4, -4/5, -5/6]])
Matrix([[3, 3, 3, 3, 3, 3], [0, -5/6, -10/11, -15/16, -20/21, -25/26], [0, 0, -4/55, -3/28, -8/63, -20/143], [0, 0, -3/77, -9/160, -6/91, -1

In [30]:
P

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.8       , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.9       , 0.05844156, 1.        , 0.        ,
        0.        ],
       [1.        , 0.96      , 0.02424242, 0.19329389, 1.        ,
        0.        ],
       [1.        , 0.        , 0.10909091, 0.49038462, 0.61136249,
        1.        ]])

In [31]:
L

⎡3   3     3     3      3        3    ⎤
⎢                                     ⎥
⎢         -10   -15    -20      -25   ⎥
⎢0  -5/6  ────  ────   ────     ────  ⎥
⎢          11    16     21       26   ⎥
⎢                                     ⎥
⎢0   0    -2/3  -3/4   -4/5     -5/6  ⎥
⎢                                     ⎥
⎢               -39   -688            ⎥
⎢0   0     0    ────  ─────    -7/143 ⎥
⎢               1540  17325           ⎥
⎢                                     ⎥
⎢                               123   ⎥
⎢0   0     0     0    2/6825   ────── ⎥
⎢                              208208 ⎥
⎢                                     ⎥
⎢                               -32   ⎥
⎢0   0     0     0      0     ────────⎥
⎣                             25882857⎦

In [ ]:
U

⎡3   3     3      3     3     3  ⎤
⎢                                ⎥
⎢0   0    -2/3  -3/4   -4/5  -5/6⎥
⎢                                ⎥
⎢                            -10 ⎥
⎢0  -2/3  -4/5  -6/7   -8/9  ────⎥
⎢                             11 ⎥
⎢                                ⎥
⎢                      -12   -15 ⎥
⎢0  -3/4  -6/7  -9/10  ────  ────⎥
⎢                       13    16 ⎥
⎢                                ⎥
⎢               -12    -16   -20 ⎥
⎢0  -4/5  -8/9  ────   ────  ────⎥
⎢                13     17    21 ⎥
⎢                                ⎥
⎢         -10   -15    -20   -25 ⎥
⎢0  -5/6  ────  ────   ────  ────⎥
⎣          11    16     21    26 ⎦

In [ ]:
P,L,U = PLU(A,2)

In [ ]:
P

⎡1  0  0  0  0  0⎤
⎢                ⎥
⎢0  0  0  0  0  1⎥
⎢                ⎥
⎢0  0  1  0  0  0⎥
⎢                ⎥
⎢0  0  0  1  0  0⎥
⎢                ⎥
⎢0  0  0  0  1  0⎥
⎢                ⎥
⎣0  1  0  0  0  0⎦

In [ ]:
L

⎡1     0    0  0  0  0⎤
⎢                     ⎥
⎢-1    1    0  0  0  0⎥
⎢                     ⎥
⎢-1  -4/5   1  0  0  0⎥
⎢                     ⎥
⎢-1  -9/10  0  1  0  0⎥
⎢                     ⎥
⎢    -24              ⎥
⎢-1  ────   0  0  1  0⎥
⎢     25              ⎥
⎢                     ⎥
⎣-1    0    0  0  0  1⎦

In [ ]:
U

⎡3   3      3       3       3      3   ⎤
⎢                                      ⎥
⎢          -10     -15    -20     -25  ⎥
⎢0  -5/6   ────    ────   ────    ──── ⎥
⎢           11      16     21      26  ⎥
⎢                                      ⎥
⎢                                 -20  ⎥
⎢0   0    -4/55   -3/28   -8/63   ──── ⎥
⎢                                 143  ⎥
⎢                                      ⎥
⎢                                 -15  ⎥
⎢0   0    -3/77   -9/160  -6/91   ──── ⎥
⎢                                 208  ⎥
⎢                                      ⎥
⎢                         -16          ⎥
⎢0   0    -8/495  -3/130  ────   -8/273⎥
⎢                         595          ⎥
⎢                                      ⎥
⎣0   0     -2/3    -3/4   -4/5    -5/6 ⎦

In [ ]:
P,L,U = PLU(A,3)

In [ ]:
P

⎡1  0  0  0  0  0⎤
⎢                ⎥
⎢0  0  0  0  0  1⎥
⎢                ⎥
⎢0  1  0  0  0  0⎥
⎢                ⎥
⎢0  0  0  1  0  0⎥
⎢                ⎥
⎢0  0  0  0  1  0⎥
⎢                ⎥
⎣0  0  1  0  0  0⎦

In [ ]:
L

⎡1     0      0     0  0  0⎤
⎢                          ⎥
⎢-1    1      0     0  0  0⎥
⎢                          ⎥
⎢-1    0      1     0  0  0⎥
⎢                          ⎥
⎢-1  -9/10  -9/154  1  0  0⎥
⎢                          ⎥
⎢    -24                   ⎥
⎢-1  ────   -4/165  0  1  0⎥
⎢     25                   ⎥
⎢                          ⎥
⎣-1  -4/5   -6/55   0  0  1⎦

In [ ]:
U

⎡3   3     3       3       3      3   ⎤
⎢                                     ⎥
⎢         -10    -15     -20     -25  ⎥
⎢0  -5/6  ────   ────    ────    ──── ⎥
⎢          11     16      21      26  ⎥
⎢                                     ⎥
⎢0   0    -2/3   -3/4    -4/5    -5/6 ⎥
⎢                                     ⎥
⎢                -153    -96    -375  ⎥
⎢0   0     0     ─────   ────   ───── ⎥
⎢                12320   5005   16016 ⎥
⎢                                     ⎥
⎢                        -736    -82  ⎥
⎢0   0     0    -7/1430  ─────   ──── ⎥
⎢                        98175   9009 ⎥
⎢                                     ⎥
⎢                -39     -688         ⎥
⎢0   0     0     ────    ─────  -7/143⎥
⎣                1540    17325        ⎦

In [ ]:
P,L,U = PLU(A,4)

In [ ]:
P

⎡1  0  0  0  0  0⎤
⎢                ⎥
⎢0  0  0  0  0  1⎥
⎢                ⎥
⎢0  1  0  0  0  0⎥
⎢                ⎥
⎢0  0  1  0  0  0⎥
⎢                ⎥
⎢0  0  0  0  1  0⎥
⎢                ⎥
⎣0  0  0  1  0  0⎦

In [ ]:
L

⎡1     0      0      0    0  0⎤
⎢                             ⎥
⎢-1    1      0      0    0  0⎥
⎢                             ⎥
⎢-1    0      1      0    0  0⎥
⎢                             ⎥
⎢-1  -4/5   -6/55    1    0  0⎥
⎢                             ⎥
⎢    -24            -98       ⎥
⎢-1  ────   -4/165  ────  1  0⎥
⎢     25            507       ⎥
⎢                             ⎥
⎢                   -51       ⎥
⎢-1  -9/10  -9/154  ────  0  1⎥
⎣                   104       ⎦

In [ ]:
U

⎡3   3     3     3       3         3   ⎤
⎢                                      ⎥
⎢         -10   -15     -20      -25   ⎥
⎢0  -5/6  ────  ────    ────     ────  ⎥
⎢          11    16      21       26   ⎥
⎢                                      ⎥
⎢0   0    -2/3  -3/4    -4/5     -5/6  ⎥
⎢                                      ⎥
⎢               -39    -688            ⎥
⎢0   0     0    ────   ─────    -7/143 ⎥
⎢               1540   17325           ⎥
⎢                                      ⎥
⎢                       2432      548  ⎥
⎢0   0     0     0    ────────  ───────⎥
⎢                     13574925  1522521⎥
⎢                                      ⎥
⎢                                123   ⎥
⎢0   0     0     0     2/6825   ────── ⎥
⎣                               208208 ⎦

In [45]:
P,L,U = PLU(A,5)

In [ ]:
P

⎡1  0  0  0  0  0⎤
⎢                ⎥
⎢0  0  0  0  0  1⎥
⎢                ⎥
⎢0  1  0  0  0  0⎥
⎢                ⎥
⎢0  0  1  0  0  0⎥
⎢                ⎥
⎢0  0  0  1  0  0⎥
⎢                ⎥
⎣0  0  0  0  1  0⎦

In [35]:
L

⎡3   3     3     3      3        3    ⎤
⎢                                     ⎥
⎢         -10   -15    -20      -25   ⎥
⎢0  -5/6  ────  ────   ────     ────  ⎥
⎢          11    16     21       26   ⎥
⎢                                     ⎥
⎢0   0    -2/3  -3/4   -4/5     -5/6  ⎥
⎢                                     ⎥
⎢               -39   -688            ⎥
⎢0   0     0    ────  ─────    -7/143 ⎥
⎢               1540  17325           ⎥
⎢                                     ⎥
⎢                               123   ⎥
⎢0   0     0     0    2/6825   ────── ⎥
⎢                              208208 ⎥
⎢                                     ⎥
⎢                               -32   ⎥
⎢0   0     0     0      0     ────────⎥
⎣                             25882857⎦

In [33]:
U

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [44]:
from sympy import  N
N(U)


AttributeError: ignored